name: Dev Provisioning and Lambda Deployment

on:
  push:
    branches:
      - 'main'
  workflow_call:
    inputs:
      environment:
        type: string
        description: "Environment to deploy to"
        default: "Dev"
      working_directory:
        type: string
        description: "The directory where code resides"
        default: "./Lambda"
      lambda_function_name:
        type: string
        description: "Name of the Lambda function to deploy"
      aws_region:
        type: string
        description: "If using AWS, the region to target. Defaults to us-east-1."
        default: "us-west-2"
      use_oidc:
        type: string
        description: "Use the OIDC provider to authenticate the provisioning process"
        default: "false"
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
 
jobs:
  build:
    name: Code build
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
 
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
 
      - name: Install Dependencies
        run: cd Lambda && npm install
        working-directory: ${{ inputs.working_directory }}
 
      - name: Build
        run: cd Lambda && ls
        working-directory: ${{ inputs.working_directory }}
 
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lambda-artifacts
          path: ./Lambda/node_modules
          working-directory: ${{ inputs.working_directory }}
 
  deploy:
    name: Code Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: lambda-artifacts
          path: ./Layers
 
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
 
      - name: Update Lambda Function Code
        run: |
          LAMBDA_FUNCTION_NAME=${{ inputs.lambda_function_name }}
          zip -r lambda_function.zip .
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://lambda_function.zip
          rm lambda_function.zip
