name: Deploy lambda function
run-name: Deploy ${{ inputs.environment }} Lambda function
 
on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: "Environment to deploy to"
        default: "dev"
      runs_on:
        type: string
        description: The runner group label to use for the actions
        default: "ubuntu-latest"
      working_directory:
        type: string
        description: "The directory where code resides"
        default: "./Lambda"
      lambda_function_name:
        type: string
        description: "Name of the Lambda function to deploy"
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true
 
jobs:
  build:
    name: Code build
    environment: ${{ inputs.environment }}
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
 
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
 
      - name: Install Dependencies
        run: npm install
 
      - name: Build
        run: npm run build 
 
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lambda-artifacts
          path: ./build
 
  deploy:
    name: Code Deploy
    environment: ${{ inputs.environment }}
    runs-on: ${{ inputs.runs_on }}
    needs: build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: lambda-artifacts
          path: ./Lambda
 
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
 
      - name: Update Lambda Function Code
        run: |
          LAMBDA_FUNCTION_NAME=${{ inputs.lambda_function_name }}
          zip -r lambda_function.zip .
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://lambda_function.zip
          rm lambda_function.zip